### ISSUE TITLE
Missing eu.chargetime.ocpp package

### ISSUE THREAD

**Issue by avinashupadhya99** [ChargeTimeEU/ChargeTime-HQ#2]
Unable to import eu.chargetime.ocpp package and I tried adding the v1_6-0.4-SNAPSHOT.jar to .m2\repository\eu\chargetime\ocpp\v1_6\0.4-SNAPSHOT. This brought up a lot of other new errors.

**Comment by avinashupadhya99** [comment]
Mistake

**Comment by TVolden** [comment]
@avinashupadhya99 sorry that I never replied, I wasn't feeling that good this weekend.

**Comment by avinashupadhya99** [comment]
> @avinashupadhya99 sorry that I never replied, I wasn't feeling that good this weekend.

That's okay. Hope you are feeling well now. I made a very grave mistake of not adding the ocpp library as a dependency. It would be very helpful if there was a documentation on how this works or comments in the code. Thank you.
